### PR TITLE
Update ipcat.csv

### PR DESCRIPTION
**Pull request by cyberlimbo**
Ipcat.csv update

### CODE REVIEW

**Comment by MikkelDK** [comment]
Can't see.. why "Gigahost.dk" is on ipcat. since they are not "VPN provider" only web hosting provider. =D

**Comment by cyberlimbo** [comment]
Some hosts are in the ipcat file and their not vpn providers (example: OVH) ;)

**Comment by MikkelDK** [comment]
Gigahost is just a "Web hosting" provider... XD but fair enough :b

**Comment by cyberlimbo** [comment]
Like i explained, some "vpn providers" are not using their own hosts..

**Pull request merged**
